import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const O = '/home/user/portail-rh/brag-output/logos/test';
const b = await chromium.launch(); const ctx = await b.newContext({ locale: 'fr-FR', viewport: { width: 1440, height: 900 }, acceptDownloads: true, deviceScaleFactor: 2 });
const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://localhost:8094/simulateur-assurance-vie/index.html', { waitUntil: 'networkidle' });
await p.waitForTimeout(1200);
await p.screenshot({ path: `${O}/vie-header.png`, clip: { x: 0, y: 0, width: 520, height: 90 } });
// install poster, generated by the app itself
await p.evaluate(() => document.getElementById('fi-affiche').click());
const dl = await p.waitForEvent('download', { timeout: 15000 }).catch(e => null);
if (dl) await dl.saveAs(`${O}/affiche.pdf`); else console.log('pas de téléchargement affiche');
// PDF report
await p.fill('#revenue', '60000'); await p.fill('#investment-amount-period', '500'); await p.locator('#investment-amount-period').press('Tab'); await p.waitForTimeout(800);
const btn = p.getByRole('button', { name: /Télécharger le rapport PDF/ }).first();
const [d2] = await Promise.all([p.waitForEvent('download', { timeout: 20000 }).catch(() => null), btn.click().catch(e => console.log('btn', e.message))]);
if (d2) await d2.saveAs(`${O}/rapport.pdf`); else console.log('pas de rapport');
console.log('erreurs:', errs.length ? errs : 'aucune');
await b.close();
